name: Slack Notify on CI Failure

on:
  workflow_call:
    inputs:
      job_name:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      run_id:
        required: true
        type: string

jobs:
  send-failure-notification:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout ci-slack-notifier repo
        uses: actions/checkout@v3
        with:
          repository: ThriveCoin/ci-slack-notifier
          ref: THC-7395

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::551683532621:role/github_actions
          aws-region: us-east-1

      - name: Read secrets from AWS Secrets Manager
        uses: abhilash1in/aws-secrets-manager-action@v2.0.0
        with:
          secrets: |
            SLACK_HOOK
          parse-json: true

      - name: Send Slack notification for failed job
        run: |
          ./scripts/notify.sh \
            "${{ env.SLACK_HOOK_DEPLOYMENT }}" \
            "${{ inputs.job_name }}" \
            "${{ inputs.repo_name }}" \
            "${{ inputs.run_id }}"